"use client"

import type React from "react"
import { useState, useRef } from "react"
import { useRouter } from "next/navigation"
import { useOKR } from "@/lib/okr-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import {
  Sparkles,
  Globe,
  Copy,
  GripVertical,
  Plus,
  Trash2,
  ArrowRight,
  Pencil,
  X,
  RefreshCw,
} from "lucide-react"
import type { Objective, CompanyProfile } from "@/lib/types"
import { researchCompany, generateLeaderOKRs, regenerateOKRsFromSummary, saveOKRsToDatabase, type LamaticObjective } from "@/lib/lamatic-api"
import { LoadingWithFacts } from "./loading-with-facts"

const generateId = () => Math.random().toString(36).substring(2, 9)

/**
 * Generate a valid UUID v4
 */
const generateUUID = (): string => {
  // Use crypto.randomUUID if available (modern browsers)
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID()
  }

  // Fallback: Generate UUID v4 manually
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0
    const v = c === 'x' ? r : (r & 0x3 | 0x8)
    return v.toString(16)
  })
}

/**
 * Get or create persistent user ID
 * This ensures the same user always gets the same ID across sessions
 */
const getPersistentUserId = (): string => {
  // Check if we're in browser environment
  if (typeof window === 'undefined') return generateUUID()

  const STORAGE_KEY = 'okr_user_id'

  // Try to get existing user ID from localStorage
  let userId = localStorage.getItem(STORAGE_KEY)

  // If no user ID exists, generate a new one and save it
  if (!userId) {
    userId = generateUUID()
    localStorage.setItem(STORAGE_KEY, userId)
    console.log('🆕 Generated new persistent user ID:', userId)
  } else {
    console.log('♻️ Retrieved existing user ID:', userId)
  }

  return userId
}

export function Screen1Kickoff() {
  const router = useRouter()
  const {
    setCompanyProfile,
    companyProfile,
    setLeaderOKRs,
    leaderOKRs,
    setShareableSummary,
    shareableSummary,
    setCurrentScreen,
    setToastMessage,
    isLoading,
    setIsLoading,
    setCurrentUser,
    currentUser,
    setPlanningPeriod,
    planningPeriod,
  } = useOKR()

  const [formData, setFormData] = useState({
    companyWebsite: "",
    roleTitle: "",
    planningPeriod: "",
    goalSummary: "Want to increase the sales of the company",
  })

  // Check if OKRs have been generated by looking at context instead of local state
  const hasGenerated = leaderOKRs.length > 0 && shareableSummary !== null
  const [isEditingSummary, setIsEditingSummary] = useState(false)
  const [editedSummaryText, setEditedSummaryText] = useState("")
  const [isRegeneratingOKRs, setIsRegeneratingOKRs] = useState(false)
  const [openPopoverId, setOpenPopoverId] = useState<string | null>(null)
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null)
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null)

  const isFormValid =
    formData.companyWebsite.length > 0 &&
    formData.roleTitle.length >= 2 &&
    formData.planningPeriod.length > 0 &&
    formData.goalSummary.length >= 20

  // Helper function to transform Lamatic objectives to frontend format
  const transformToObjectives = (lamaticObjectives: LamaticObjective[]): Objective[] => {
    return lamaticObjectives.map((obj) => ({
      objectiveId: generateId(),
      title: obj.title,
      description: obj.description,
      rank: parseInt(obj.order_index) || 0,
      confidence: "medium" as const,
      keyResults: obj.key_results.map((kr) => ({
        krId: generateId(),
        text: kr.title,
        target: kr.target_value,
        unit: kr.unit,
        actual: kr.baseline_value,
        progress: 0,
      })),
    }))
  }

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!isFormValid) return

    setIsLoading(true)

    try {
      // Ensure the website URL has https:// prefix
      let websiteUrl = formData.companyWebsite.trim()
      if (!websiteUrl.startsWith('http://') && !websiteUrl.startsWith('https://')) {
        websiteUrl = `https://${websiteUrl}`
      }

      // STEP 1: Research company (Flow 1)
      const companyData = await researchCompany(websiteUrl)

      // Extract domain from website URL
      const domain = websiteUrl.replace(/^https?:\/\//, "").replace(/\/$/, "")

      // Store company profile in context
      const profile: CompanyProfile = {
        domain,
        name: companyData.company_profile.company_name,
        industry: companyData.company_profile.industry,
        size: companyData.company_profile.employee_count,
        publicNotes: companyData.company_profile.mission || "Researched via Lamatic",
        products: companyData.company_profile.products,
        employee_count: companyData.company_profile.employee_count,
        headquarters: companyData.company_profile.headquarters,
        founded_year: companyData.company_profile.founded_year,
        key_features: companyData.company_profile.key_features,
        mission: companyData.company_profile.mission,
      }

      setCompanyProfile(profile)
      setPlanningPeriod(formData.planningPeriod)

      // Set current user with PERSISTENT ID
      // This ensures the same user gets the same ID across multiple OKR generations
      const persistentUserId = getPersistentUserId()
      const newUser = {
        userId: persistentUserId,
        name: formData.roleTitle.split(" ").pop() || "Leader",
        email: `leader@${domain}`,
        role: formData.roleTitle,
        companyDomain: domain,
      }
      console.log('👤 User created with persistent ID:', {
        userId: newUser.userId,
        email: newUser.email,
        role: newUser.role,
      })
      setCurrentUser(newUser)

      // STEP 2: Generate OKRs (Flow 2) - uses Flow 1 output
      const okrData = await generateLeaderOKRs({
        company_profile: companyData.company_profile,
        user_role: formData.roleTitle,
        user_goals: formData.goalSummary,
        planning_period: formData.planningPeriod,
        website_data: companyData.website_data || "", // Raw markdown from Firecrawl
      })

      // Transform and store results
      const objectives = transformToObjectives(okrData.okr_plan.objectives)
      setLeaderOKRs(objectives)

      setShareableSummary({
        title: `${formData.planningPeriod} Strategic Priorities — ${formData.roleTitle}, ${profile.name}`,
        text: okrData.okr_plan.strategic_narrative,
        shortlink: `https://lmtc.ai/s/${generateId()}`,
      })

      setToastMessage("Leader OKRs generated successfully!")
      setIsLoading(false) // Stop loading immediately to show OKRs

      // STEP 3: Save OKRs to database (Flow 4) - Run in background, non-blocking
      const savePayload = {
        user_id: newUser.userId,
        user_email: newUser.email,
        user_name: newUser.name,
        user_role: newUser.role,
        website_url: websiteUrl,
        company_name: profile.name,
        planning_period: formData.planningPeriod,
        okr_plan: {
          strategic_narrative: okrData.okr_plan.strategic_narrative,
          objectives: okrData.okr_plan.objectives, // Send as array, not stringified
        },
      }
      console.log('💾 Saving OKRs to database with payload:', {
        user_id: savePayload.user_id,
        user_email: savePayload.user_email,
        user_name: savePayload.user_name,
        user_role: savePayload.user_role,
        company_name: savePayload.company_name,
        planning_period: savePayload.planning_period,
        objectives_count: okrData.okr_plan.objectives.length,
      })

      saveOKRsToDatabase(savePayload)
        .then((saveResult) => {
          console.log('✅ OKRs saved to database:', saveResult)
          if (saveResult.success) {
            console.log('🎉 Database save successful! Check Supabase for user_id:', newUser.userId)
          } else {
            console.error('❌ Database save failed:', saveResult.message)
          }
        })
        .catch((saveError) => {
          console.error('⚠️ Failed to save OKRs to database:', saveError)
          // Silent failure - don't disrupt user experience
        })

    } catch (error) {
      console.error("Error generating OKRs:", error)
      setToastMessage("Failed to generate OKRs. Please check your website URL and try again.")
      setIsLoading(false)
    }
  }

  const handleStartEditSummary = () => {
    if (shareableSummary) {
      setEditedSummaryText(shareableSummary.text)
      setIsEditingSummary(true)
    }
  }

  const handleSaveSummaryAndRegenerate = async () => {
    if (!shareableSummary || editedSummaryText === shareableSummary.text || !companyProfile) {
      setIsEditingSummary(false)
      return
    }

    setIsRegeneratingOKRs(true)

    // Update summary immediately
    setShareableSummary({
      ...shareableSummary,
      text: editedSummaryText,
    })

    try {
      // STEP 3: Regenerate OKRs from edited narrative (Flow 3)
      const okrData = await regenerateOKRsFromSummary({
        company_profile: {
          company_name: companyProfile.name,
          industry: companyProfile.industry,
          products: companyProfile.products || [],
          mission: companyProfile.mission || "",
          employee_count: companyProfile.employee_count || "",
          headquarters: companyProfile.headquarters || "",
          founded_year: companyProfile.founded_year || "",
          key_features: companyProfile.key_features || [],
        },
        user_role: formData.roleTitle,
        planning_period: formData.planningPeriod,
        edited_narrative: editedSummaryText,
      })

      // Transform and update OKRs
      const objectives = transformToObjectives(okrData.okr_plan.objectives)
      setLeaderOKRs(objectives)

      setIsEditingSummary(false)
      setToastMessage("Summary updated and OKRs regenerated successfully!")

      // STEP 4: Save regenerated OKRs to database (Flow 4)
      // Run this in the background after showing success to the user
      if (currentUser && planningPeriod) {
        console.log('💾 Saving regenerated OKRs to database...')
        // Ensure website URL has https:// prefix for consistency
        let websiteUrl = companyProfile.domain
        if (!websiteUrl.startsWith('http://') && !websiteUrl.startsWith('https://')) {
          websiteUrl = `https://${websiteUrl}`
        }

        const savePayload = {
          user_id: currentUser.userId,
          user_email: currentUser.email,
          user_name: currentUser.name,
          user_role: currentUser.role,
          website_url: websiteUrl,
          company_name: companyProfile.name,
          planning_period: planningPeriod,
          okr_plan: {
            strategic_narrative: editedSummaryText, // Use the updated narrative
            objectives: okrData.okr_plan.objectives, // Send as array, not stringified
          },
        }

        console.log('📤 Payload for regenerated OKRs:', {
          user_id: savePayload.user_id,
          user_email: savePayload.user_email,
          company_name: savePayload.company_name,
          planning_period: savePayload.planning_period,
          objectives_count: okrData.okr_plan.objectives.length,
          narrative_preview: editedSummaryText.substring(0, 100) + '...',
        })

        saveOKRsToDatabase(savePayload)
          .then((saveResult) => {
            console.log('✅ Regenerated OKRs saved to database:', saveResult)
            if (saveResult.success) {
              console.log('🎉 Database update successful! User ID:', currentUser.userId)
            } else {
              console.error('❌ Database save failed:', saveResult.message)
            }
          })
          .catch((saveError) => {
            console.error('⚠️ Failed to save regenerated OKRs to database:', saveError)
            // Silent failure - don't disrupt user experience
          })
      } else {
        console.warn('⚠️ Cannot save regenerated OKRs: Missing currentUser or planningPeriod')
      }
    } catch (error) {
      console.error("Error regenerating OKRs:", error)
      setToastMessage("Failed to regenerate OKRs. Please try again.")
    } finally {
      setIsRegeneratingOKRs(false)
    }
  }

  const handleCancelEditSummary = () => {
    setIsEditingSummary(false)
    setEditedSummaryText("")
  }

  const updateObjective = (objectiveId: string, field: string, value: string) => {
    setLeaderOKRs(leaderOKRs.map((obj) => (obj.objectiveId === objectiveId ? { ...obj, [field]: value } : obj)))
  }

  const handleDragStart = (index: number) => {
    setDraggedIndex(index)
  }

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault()
    setDragOverIndex(index)
  }

  const handleDrop = (e: React.DragEvent, dropIndex: number) => {
    e.preventDefault()
    if (draggedIndex === null) return

    const newOKRs = [...leaderOKRs]
    const [draggedItem] = newOKRs.splice(draggedIndex, 1)
    newOKRs.splice(dropIndex, 0, draggedItem)

    setLeaderOKRs(newOKRs)
    setDraggedIndex(null)
    setDragOverIndex(null)
  }

  const handleDragEnd = () => {
    setDraggedIndex(null)
    setDragOverIndex(null)
  }

  const updateKeyResult = (objectiveId: string, krId: string, field: string, value: string | number) => {
    setLeaderOKRs(
      leaderOKRs.map((obj) =>
        obj.objectiveId === objectiveId
          ? {
            ...obj,
            keyResults: obj.keyResults.map((kr) => (kr.krId === krId ? { ...kr, [field]: value } : kr)),
          }
          : obj,
      ),
    )
  }

  const addKeyResult = (objectiveId: string) => {
    setLeaderOKRs(
      leaderOKRs.map((obj) =>
        obj.objectiveId === objectiveId
          ? {
            ...obj,
            keyResults: [
              ...obj.keyResults,
              { krId: generateId(), text: "", target: 100, unit: "%", actual: 0, progress: 0 },
            ],
          }
          : obj,
      ),
    )
    setToastMessage("Key result added successfully!")
  }

  const removeKeyResult = (objectiveId: string, krId: string) => {
    setLeaderOKRs(
      leaderOKRs.map((obj) =>
        obj.objectiveId === objectiveId ? { ...obj, keyResults: obj.keyResults.filter((kr) => kr.krId !== krId) } : obj,
      ),
    )
  }

  const removeObjective = (objectiveId: string) => {
    setLeaderOKRs(leaderOKRs.filter((obj) => obj.objectiveId !== objectiveId))
  }

  const addObjective = () => {
    const newObjective: Objective = {
      objectiveId: generateId(),
      title: "",
      rank: leaderOKRs.length + 1,
      confidence: "medium",
      keyResults: [{ krId: generateId(), text: "", target: 100, unit: "%", actual: 0, progress: 0 }],
    }
    setLeaderOKRs([...leaderOKRs, newObjective])
    setToastMessage("Objective created successfully!")
  }

  const handleCopyToClipboard = () => {
    if (shareableSummary) {
      navigator.clipboard.writeText(`${shareableSummary.title}\n\n${shareableSummary.text}`)
      setToastMessage("Copied to clipboard!")
    }
  }

  const handleContinue = () => {
    router.push('/edit')
  }

  return (
    <div className="max-w-xl mx-auto space-y-8">
      {/* Show loading with facts during initial generation */}
      {isLoading && !hasGenerated && (
        <LoadingWithFacts message="Analyzing and generating OKRs..." />
      )}

      {/* Intake Form - only show when not loading and not generated */}
      {!isLoading && !hasGenerated && (
        <Card className="border-border/50 bg-card/50 backdrop-blur">
          <CardHeader className="text-center pb-2">
            <div className="mx-auto p-3 rounded-xl bg-[#DC2626]/10 w-fit mb-4">
              <Globe className="w-8 h-8 text-[#DC2626]" />
            </div>
            <CardTitle className="text-2xl">
              Create your OKRs
            </CardTitle>
            <CardDescription className="max-w-md mx-auto">
              We'll analyze your company and generate strategic OKRs tailored to your role and goals.
            </CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            <form onSubmit={handleGenerate} className="flex flex-col gap-5">
              <div className="space-y-2">
                <Label htmlFor="companyWebsite">Company Website</Label>
                <Input
                  id="companyWebsite"
                  type="text"
                  placeholder="http://example.com"
                  value={formData.companyWebsite}
                  onChange={(e) => setFormData((prev) => ({ ...prev, companyWebsite: e.target.value }))}
                  required
                />
                <p className="text-xs text-muted-foreground">Enter your company website (we'll add https:// if needed)</p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="roleTitle">Your Role / Title</Label>
                <Input
                  id="roleTitle"
                  placeholder="VP Product, Head of Sales..."
                  value={formData.roleTitle}
                  onChange={(e) => setFormData((prev) => ({ ...prev, roleTitle: e.target.value }))}
                  required
                  minLength={2}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="planningPeriod">Planning Period</Label>
                <Select
                  value={formData.planningPeriod}
                  onValueChange={(value) => setFormData((prev) => ({ ...prev, planningPeriod: value }))}
                  required
                >
                  <SelectTrigger id="planningPeriod">
                    <SelectValue placeholder="Select period" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Q1 2026">Q1 2026</SelectItem>
                    <SelectItem value="Q2 2026">Q2 2026</SelectItem>
                    <SelectItem value="H1 2026">H1 2026</SelectItem>
                    <SelectItem value="FY 2026">FY 2026</SelectItem>
                    <SelectItem value="Custom">Custom</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="goalSummary">Top 2-3 goals for this period</Label>
                <Textarea
                  id="goalSummary"
                  placeholder="Describe your key goals and priorities for this planning period..."
                  value={formData.goalSummary}
                  onChange={(e) => setFormData((prev) => ({ ...prev, goalSummary: e.target.value }))}
                  rows={4}
                  required
                  minLength={20}
                  maxLength={500}
                  className="resize-none"
                />
                <p className="text-xs text-muted-foreground text-right">{formData.goalSummary.length}/500 characters</p>
              </div>

              <Button type="submit" className="w-full h-12 text-base" disabled={!isFormValid || isLoading}>
                <Sparkles className="w-5 h-5 mr-2" />
                Generate OKRs
              </Button>

              <p className="text-xs text-muted-foreground text-center">
                By continuing you agree Lamatic may analyze public information to generate OKR suggestions.
              </p>
            </form>
          </CardContent>
        </Card>
      )}

      {/* Show loading with facts during regeneration */}
      {isRegeneratingOKRs && (
        <LoadingWithFacts message="Regenerating your OKRs..." />
      )}

      {/* Generated OKRs - hide during regeneration */}
      {hasGenerated && !isRegeneratingOKRs && (
        <div className="max-w-4xl mx-auto space-y-8">
          {shareableSummary && (
            <Card className="border-[#DC2626]/20 bg-[#DC2626]/5">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-[#DC2626]" />
                    <CardTitle className="text-lg">{shareableSummary.title}</CardTitle>
                  </div>
                  {!isEditingSummary && (
                    <Button variant="ghost" size="sm" onClick={handleStartEditSummary}>
                      <Pencil className="w-4 h-4 mr-2" />
                      Edit
                    </Button>
                  )}
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="p-4 rounded-lg bg-card border border-border">
                  {isEditingSummary ? (
                    <Textarea
                      value={editedSummaryText}
                      onChange={(e) => setEditedSummaryText(e.target.value)}
                      rows={6}
                      className="resize-none"
                      placeholder="Describe your strategic priorities..."
                    />
                  ) : (
                    <p className="text-sm text-muted-foreground whitespace-pre-line">{shareableSummary.text}</p>
                  )}
                </div>

                {isEditingSummary ? (
                  <div className="flex flex-col gap-2">
                    <Button onClick={handleSaveSummaryAndRegenerate} disabled={isRegeneratingOKRs} className="w-full">
                      <RefreshCw className="w-4 h-4 mr-2" />
                      Save & Regenerate OKRs
                    </Button>
                    <Button variant="outline" onClick={handleCancelEditSummary} disabled={isRegeneratingOKRs}>
                      <X className="w-4 h-4 mr-2" />
                      Cancel
                    </Button>
                  </div>
                ) : (
                  <Button variant="outline" size="sm" onClick={handleCopyToClipboard} className="w-full bg-transparent">
                    <Copy className="w-4 h-4 mr-2" />
                    Copy to Clipboard
                  </Button>
                )}
              </CardContent>
            </Card>
          )}

          {/* Leader OKRs */}
          <Card className="border-border/50 bg-card/50 backdrop-blur">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-xl">Your OKRs</CardTitle>
                  <CardDescription>Edit objectives and key results, then continue to invite your team.</CardDescription>
                </div>
                <Button variant="outline" size="sm" onClick={addObjective}>
                  <Plus className="w-4 h-4 mr-2" />
                  Add Objective
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-6">
              {leaderOKRs.map((objective, objIndex) => (
                <div
                  key={objective.objectiveId}
                  draggable
                  onDragStart={() => handleDragStart(objIndex)}
                  onDragOver={(e) => handleDragOver(e, objIndex)}
                  onDrop={(e) => handleDrop(e, objIndex)}
                  onDragEnd={handleDragEnd}
                  className={`p-4 rounded-lg border border-border bg-background/50 space-y-4 transition-all ${
                    draggedIndex === objIndex ? 'opacity-50' : ''
                  } ${
                    dragOverIndex === objIndex && draggedIndex !== objIndex ? 'border-primary' : ''
                  }`}
                >
                  <div className="flex items-start gap-3">
                    <GripVertical className="w-5 h-5 text-muted-foreground mt-2 cursor-grab shrink-0 hover:text-primary" />
                    <div className="flex-1 space-y-4">
                      <div className="flex items-center gap-2">
                        <Badge variant="secondary" className="shrink-0">
                          O{objIndex + 1}
                        </Badge>
                        <Popover open={openPopoverId === `obj-${objective.objectiveId}`} onOpenChange={(open) => setOpenPopoverId(open ? `obj-${objective.objectiveId}` : null)}>
                          <PopoverTrigger asChild>
                            <div className="flex-1">
                              <Input
                                value={objective.title}
                                onChange={(e) => updateObjective(objective.objectiveId, "title", e.target.value)}
                                placeholder="Enter objective..."
                                className={objective.title && objective.title.length > 30 ? "cursor-pointer" : ""}
                              />
                            </div>
                          </PopoverTrigger>
                          {objective.title && objective.title.length > 30 && (
                            <PopoverContent className="w-96 p-3" align="start">
                              <p className="text-sm break-words">{objective.title}</p>
                            </PopoverContent>
                          )}
                        </Popover>
                        <Select
                          value={objective.confidence || "medium"}
                          onValueChange={(value) => updateObjective(objective.objectiveId, "confidence", value)}
                        >
                          <SelectTrigger
                            className={`w-32 h-7 text-xs font-medium ${
                              objective.confidence === "highest"
                                ? "bg-[#DC2626]/20 text-[#DC2626] border-[#DC2626]/40"
                                : objective.confidence === "high"
                                  ? "bg-orange-500/20 text-orange-500 border-orange-500/40"
                                  : objective.confidence === "medium"
                                    ? "bg-yellow-500/20 text-yellow-500 border-yellow-500/40"
                                    : objective.confidence === "low"
                                      ? "bg-blue-500/20 text-blue-500 border-blue-500/40"
                                      : "bg-gray-500/20 text-gray-500 border-gray-500/40"
                            }`}
                          >
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="highest" className="text-[#DC2626] font-medium">
                              <span className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-[#DC2626]"></span>
                                Highest
                              </span>
                            </SelectItem>
                            <SelectItem value="high" className="text-orange-500 font-medium">
                              <span className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-orange-500"></span>
                                High
                              </span>
                            </SelectItem>
                            <SelectItem value="medium" className="text-yellow-500 font-medium">
                              <span className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-yellow-500"></span>
                                Medium
                              </span>
                            </SelectItem>
                            <SelectItem value="low" className="text-blue-500 font-medium">
                              <span className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                                Low
                              </span>
                            </SelectItem>
                            <SelectItem value="lowest" className="text-gray-500 font-medium">
                              <span className="flex items-center gap-2">
                                <span className="w-2 h-2 rounded-full bg-gray-500"></span>
                                Lowest
                              </span>
                            </SelectItem>
                          </SelectContent>
                        </Select>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => removeObjective(objective.objectiveId)}
                          className="text-muted-foreground hover:text-destructive shrink-0"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>

                      <div className="space-y-3 pl-4">
                        {objective.keyResults.map((kr, krIndex) => (
                          <div key={kr.krId} className="flex items-center gap-2">
                            <span className="text-xs text-muted-foreground w-8 shrink-0">KR{krIndex + 1}</span>
                            <Popover open={openPopoverId === `kr-${kr.krId}`} onOpenChange={(open) => setOpenPopoverId(open ? `kr-${kr.krId}` : null)}>
                              <PopoverTrigger asChild>
                                <div className="flex-1">
                                  <Input
                                    value={kr.text}
                                    onChange={(e) => updateKeyResult(objective.objectiveId, kr.krId, "text", e.target.value)}
                                    placeholder="Key result description..."
                                    className={kr.text && kr.text.length > 30 ? "cursor-pointer" : ""}
                                  />
                                </div>
                              </PopoverTrigger>
                              {kr.text && kr.text.length > 30 && (
                                <PopoverContent className="w-96 p-3" align="start">
                                  <p className="text-sm break-words">{kr.text}</p>
                                </PopoverContent>
                              )}
                            </Popover>
                            <Popover open={openPopoverId === `target-${kr.krId}`} onOpenChange={(open) => setOpenPopoverId(open ? `target-${kr.krId}` : null)}>
                              <PopoverTrigger asChild>
                                <div className="flex items-center gap-2">
                                  <Input
                                    type="number"
                                    value={kr.target}
                                    onChange={(e) =>
                                      updateKeyResult(objective.objectiveId, kr.krId, "target", Number(e.target.value))
                                    }
                                    className="w-20"
                                    onClick={(e) => {
                                      e.stopPropagation()
                                      setOpenPopoverId(`target-${kr.krId}`)
                                    }}
                                  />
                                  <Input
                                    value={kr.unit}
                                    onChange={(e) => updateKeyResult(objective.objectiveId, kr.krId, "unit", e.target.value)}
                                    placeholder="unit"
                                    className="w-20"
                                    onClick={(e) => {
                                      e.stopPropagation()
                                      setOpenPopoverId(`target-${kr.krId}`)
                                    }}
                                  />
                                </div>
                              </PopoverTrigger>
                              <PopoverContent className="w-96 p-3" align="end">
                                <div className="space-y-2">
                                  <p className="text-sm font-medium">Key Result {krIndex + 1}</p>
                                  <p className="text-sm text-foreground break-words">{kr.text}</p>
                                  <p className="text-xs text-[#DC2626] font-semibold mt-2">Target: {kr.target} {kr.unit}</p>
                                </div>
                              </PopoverContent>
                            </Popover>
                            {objective.keyResults.length > 1 && (
                              <Button
                                variant="ghost"
                                size="icon"
                                onClick={() => removeKeyResult(objective.objectiveId, kr.krId)}
                                className="text-muted-foreground hover:text-destructive h-8 w-8 shrink-0"
                              >
                                <Trash2 className="w-3 h-3" />
                              </Button>
                            )}
                          </div>
                        ))}
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => addKeyResult(objective.objectiveId)}
                          className="text-muted-foreground"
                        >
                          <Plus className="w-3 h-3 mr-1" />
                          Add Key Result
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>

          {/* Continue Button */}
          <Button size="lg" onClick={handleContinue} className="w-full gap-2">
            Continue to Invite Team
            <ArrowRight className="w-4 h-4" />
          </Button>
        </div>
      )}
    </div>
  )
}
